# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-terragrunt-state-170940374732"
    dynamodb_table = "terraform-terragrunt-locks"
    encrypt        = true
    key            = "environments/dev/networking/terraform.tfstate"
    region         = "us-east-1"
  }
}
