# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Project     = "Terraform-Terragrunt-Infrastructure"
      ManagedBy   = "Terragrunt"
      Environment = var.environment
      Owner       = "DevOps Team"
      CreatedBy   = "Terraform"
    }
  }
}
